### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sin-dientes-activity#1]

**Comment by Aniket21mathur** [comment]
@quozl can you please assign this issue to me?Thanks.

**Comment by quozl** [comment]
You are welcome to work on this; but please say here if you stop working on it, see [Step down considerately](https://github.com/sugarlabs/sugar-docs/blob/master/src/CODE_OF_CONDUCT.md#step-down-considerately).

GitHub Assignees button only suggests Sugar Labs organisation members, sorry.

In general we don't coordinate work by assigning, mostly because there are too few people willing to do the work; what matters is the pull request, see [Contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing), quoting;
> no need to ask permission to work on an issue. You should check for pull requests linked to an issue you are addressing; if there are none, then assume nobody has done anything. Begin to fix the problem, test, make your commits, push your commits, then make a pull request. Mention an issue number in the pull request, but not the commit message. These practices allow the competition of ideas (Sugar Labs is a meritocracy).

**Comment by Aniket21mathur** [comment]
Thanks @quozl.I will follow the step down considerately.
