### ISSUE TITLE
Back button absent

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/sin-dientes-activity#10]
On clicking 'Categoría Personalizada' button in the activity there is no way back.No back button is present in the activity window.
![imageedit_2_6155551228](https://user-images.githubusercontent.com/35092582/50740207-f3c40f80-1210-11e9-9b11-06bf4a6b0020.gif)
![screenshot from 2019-01-06 23-08-32](https://user-images.githubusercontent.com/35092582/50740211-f888c380-1210-11e9-8684-dfdfda45acdc.png)

**Comment by Aniket21mathur** [comment]
@quozl  what you have to say in this?
Thanks!

**Comment by quozl** [comment]
Thanks for noticing the problem.
