### ISSUE TITLE
 Fix categories comboTextBox

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/sin-dientes-activity#12]
![screenshot from 2019-01-07 08-35-22](https://user-images.githubusercontent.com/35092582/50923630-7e0bae00-1473-11e9-9488-6fd25c1d4c12.png)
The categories combo text box is expected to show all the categories.But only shows the category which was appended first.On clicking the box arrow the box expands but only shows "Animales" until and unless the user scroll downs in the box.

**Comment by quozl** [comment]
Thanks.  Steps to reproduce?

**Comment by Aniket21mathur** [comment]
Click on "Agregar lista de palabra" in the menu section.
![screenshot from 2019-01-10 02-45-20](https://user-images.githubusercontent.com/35092582/50929018-30e30880-1482-11e9-92e7-61976b22272f.png)
On clicking on the combo box the box pops up but only shows  "Animales" untill and less the user scrolls down.This might lead the user to think that other categories are not available.
Thanks!

**Comment by quozl** [comment]
Thanks.  I wasn't aware of that feature.  I don't read Spanish, so I'm not really sure what the feature is for yet.  I'm not very familiar with the activity.

**Comment by Aniket21mathur** [comment]
The Issue did not point to a bug or a major fix in the activity but to a change in the behaviour of comboTextBox.
