### ISSUE TITLE
Categories could be in resources

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sin-dientes-activity#2]
Category titles are hard coded; they could be in the resources files instead.

**Comment by Aniket21mathur** [comment]
![imageedit_2_6155551228](https://user-images.githubusercontent.com/35092582/50740246-6cc36700-1211-11e9-9bed-7dd586cc7b5f.gif)
@quozl Are you talking about these titles?
If yes how exactly do you want them to be present in the resources files.
Thanks!

**Comment by quozl** [comment]
I've no specific requirement, other than that they not be in the program.  That way, when the resources files are changed there is no need to change the program as well.  Also consider #3.

**Comment by Aniket21mathur** [comment]
Thanks @quozl .I will look into it :smile:

**Comment by Aniket21mathur** [comment]
@quozl can you please tell me how the files at the below path are created?
"/home/guest/.sugar/default/org.laptop.Sindiente/data/nivel1.palabra".
Thanks!

**Comment by Aniket21mathur** [comment]
@quozl not only categories there is also a lot other text in spanish like button names and instructions which are hard coded in the "activity.py" file what do you recommend could they be also in the resources file?
Thanks!

**Comment by quozl** [comment]
> can you please tell me how the files at the below path are created?

I made wrong answer before.  I think these files are created with a text editor.
