### ISSUE TITLE
No copyright or license in source code

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sin-dientes-activity#5]

**Comment by quozl** [comment]
Also occurs in https://github.com/YaderV/sindientes

**Comment by Aniket21mathur** [comment]
@quozl can you please review it.Thanks!

**Comment by quozl** [comment]
Not much I can do, I'm not a copyright owner.

Also, please don't add multiple notifications.  One notification is enough.

**Comment by Aniket21mathur** [comment]
Sorry I will take care of that notification thing :sweat_smile: .
